// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbUQQDuiDwmtsScMzIKDbLBDGx0WHHr2I',
    appId: '1:1040793037595:web:7b265e5607ba7f4de441be',
    messagingSenderId: '1040793037595',
    projectId: 'instagramskillbox',
    authDomain: 'instagramskillbox.firebaseapp.com',
    storageBucket: 'instagramskillbox.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4DU9m2GN5iiWtDaceQtZqpugdPQz2UQA',
    appId: '1:1040793037595:android:c31d669571040e6ee441be',
    messagingSenderId: '1040793037595',
    projectId: 'instagramskillbox',
    storageBucket: 'instagramskillbox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-PFYli4oBpRvvVNBUzmhEbyQsDSD9Bk',
    appId: '1:1040793037595:ios:894c35c82a86b85be441be',
    messagingSenderId: '1040793037595',
    projectId: 'instagramskillbox',
    storageBucket: 'instagramskillbox.appspot.com',
    iosClientId: '1040793037595-griun1m4slp83a4ukeh4pfrrj822i4a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramSkillbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-PFYli4oBpRvvVNBUzmhEbyQsDSD9Bk',
    appId: '1:1040793037595:ios:894c35c82a86b85be441be',
    messagingSenderId: '1040793037595',
    projectId: 'instagramskillbox',
    storageBucket: 'instagramskillbox.appspot.com',
    iosClientId: '1040793037595-griun1m4slp83a4ukeh4pfrrj822i4a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramSkillbox',
  );
}
